#pragma once

typedef enum {
	StrID_NONE,
	StrID_Name,
	StrID_Description,
	StrID_BlurType_Param_Name,
	StrID_BlurType_Choices,
	StrID_Center_Param_Name,
	StrID_OuterBlur_Param_Name,
	StrID_OuterStrength_Param_Name,
	StrID_OuterEdgeFade_Param_Name,
	StrID_Blank_Param_Name,
	StrID_InnerBlur_Param_Name,
	StrID_InnerOffsetMode_Param_Name,
	StrID_InnerOffset_Param_Name,
	StrID_OuterOffsetMode_Param_Name,
	StrID_OffsetMode_Choices,
	StrID_OuterOffset_Param_Name,
	StrID_InnerStrength_Param_Name,
	StrID_RepeatBorder_Param_Name,
	StrID_InnerEdgeFade_Param_Name,
	StrID_Ellipse_Param_Name,
	StrID_Ratio_Param_Name,
	StrID_Angle_Param_Name,
	StrID_Quality_Param_Name,
	StrID_BrightnessGain_Param_Name,
	StrID_SizeVariation_Param_Name,
	StrID_NoiseParams_Param_Name,
	StrID_NoiseVariation_Param_Name,
	StrID_NoiseType_Param_Name,
	StrID_NoiseType_Choices,
	StrID_NoiseLayer_Param_Name,
	StrID_Seed_Param_Name,
	StrID_NoiseOffset_Param_Name,
	StrID_Thickness_Param_Name,
	StrID_NUMTYPES
} StrIDType;
