#!/usr/bin/env python3
"""Connect PF_Cmd_RENDER fallback to the proven typed writer path."""
import json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/"refs/conformance/olmcolorkey_effectmain_fallback_typed_writer_connection_20260805.json"
def main():
 run=subprocess.run(["python3",str(ROOT/"tools/emulation/test_olmcolorkey_mac_smartrender_adapter_20260717.py")],cwd=ROOT,capture_output=True,text=True); adapter=json.loads(run.stdout) if run.returncode==0 else {}; connection=json.loads((ROOT/"refs/conformance/olmcolorkey_entry_writer_installed_connection_20260805.json").read_text()); rows=[]; passed=run.returncode==0 and connection["status"]=="pass"
 for fmt in ("PF8","PF16","PF32"):
  row=next((c for c in adapter.get("cases",[]) if c["case"]==f"enabled_black_key_edge_blur_2_center_{fmt.lower()}"),{}); contract=row.get("numerical_contract",{}); gates={"effectmain_render_invoked_once":contract.get("effectmain_render_fallback_invocations")==1,"fallback_smart_full_buffer_byte_exact":contract.get("fallback_smart_active_and_padding_byte_exact") is True,"typed_numerical_contract_present":any(k in contract for k in ("alpha8","alpha16","alpha32")),"padding_preserved":row.get("input_padding_preserved") is True and row.get("output_padding_preserved") is True}; passed &= all(gates.values()); rows.append({"pixel_format":fmt,"gates":gates})
 gates={"all_depth_fallback_cases":all(all(r["gates"].values()) for r in rows),"actual_entry_worker_writer_connected":connection["gates"]["actual_entry_worker_writer_all_depths"],"accepted_source_installed_sections_exact":connection["gates"]["accepted_source_installed_text_const_exact"],"installed_codesign_universal":connection["gates"]["installed_codesign_valid"] and connection["gates"]["installed_universal"]}; passed &= all(gates.values())
 report={"status":"pass" if passed else "fail","closed_boundary":"For the independent center-key PF8/PF16/PF32 fixture, public EffectMain PF_Cmd_RENDER reaches RenderWorld's typed writer and produces a full-buffer byte-exact result to the proven SmartRender path; accepted identity-manifest source sections equal the installed bundle.","remaining_boundary":"No arbitrary geometry/parameter or current AE-host render claim.","installed_sha256":connection["installed"]["sha256"],"cases":rows,"connection_gates":gates}; OUT.write_text(json.dumps(report,indent=2,sort_keys=True)+"\n"); print(json.dumps({"status":report["status"],"json":str(OUT)})); return 0 if passed else 1
if __name__=="__main__": raise SystemExit(main())
