#!/usr/bin/env python3
"""Palette ownership x closed Gamma/key/smoothing covering matrix."""
from __future__ import annotations
import hashlib,json,subprocess,tempfile
from pathlib import Path
import test_olmsmoother2_geometry_classifier_matrix_actual_aex_20260811 as base
ROOT=Path(__file__).resolve().parents[2];HARNESS=ROOT/'tools/emulation/olmsmoother2_palette_ownership_covering_production_harness_20260812.cpp';SOURCE=ROOT/'mac/OLMSmoother2/Mac/OLMSmoother2_port.cpp';REPORT=ROOT/'refs/conformance/olmsmoother2_palette_ownership_covering_actual_aex_20260812.json';DOC=ROOT/'refs/conformance/olmsmoother2_palette_ownership_covering_actual_aex_20260812.md';W,H=9,7
K=base.f32(1/255);NORMAL=[(1.,0.,0.,1.),(K,K,K,1.),(0.,0.,1.,1.),(0.,1.,0.,1.),(1.,1.,0.,1.)];REORDERED=[NORMAL[4],NORMAL[3],NORMAL[1],NORMAL[0],NORMAL[2]];DUPLICATE=[NORMAL[0],NORMAL[1],NORMAL[0],NORMAL[1],NORMAL[2]]
TUPLES=[('count1_gamma1_keyoff_default',1,NORMAL,'key_off',1.,100,2,0),('count1_gamma24_noninvert_mixed',1,NORMAL,'colors_noninvert',2.4,50,50,50),('count1_gamma1_invert_mixed',1,NORMAL,'colors_invert',1.,50,50,50),('count5_normal_gamma24_keyoff_mixed',5,NORMAL,'key_off',2.4,50,50,50),('count5_reordered_gamma1_noninvert_default',5,REORDERED,'colors_noninvert',1.,100,2,0),('count5_duplicate_gamma24_invert_default',5,DUPLICATE,'colors_invert',2.4,100,2,0)]
def req(x,m):
 if not x:raise RuntimeError('FAIL CLOSED: '+m)
def main():
 with tempfile.TemporaryDirectory(prefix='sm2_palette_cover_') as td:
  binary=Path(td)/'h';subprocess.run(['clang++','-std=c++17','-O2','-I',str(ROOT/'cli/OLMSmoother2/shim'),'-I',str(ROOT/'mac/OLMSmoother2/Mac'),str(HARNESS),'-o',str(binary)],check=True);rows=[]
  for ti,(name,count,palette,key_mode,gamma,s,r,e) in enumerate(TUPLES):
   pal=palette[:count]
   for depth,(pixel_size,pad) in base.DEPTHS.items():
    pixels=base.encoded(depth,'diagonal',W,H,'gamma_colors');actual,plane,ci,wi=base.actual(depth,2,pixels,pad,W,H,s,r,e,'gamma_colors',gamma,None,pal,key_mode);out=subprocess.run([str(binary),str(ti),depth],check=True,text=True,capture_output=True).stdout;production=bytes.fromhex(dict(line.split(' ',1) for line in out.splitlines())['RAW']);req(actual==production,f'{name}/{depth}');rb=W*pixel_size+pad;req(all(actual[y*rb+W*pixel_size:(y+1)*rb]==b'\xa5'*pad for y in range(H)),f'{name}/{depth} padding');rows.append({'tuple':name,'depth':depth,'palette_count':count,'palette_rgba':pal,'key_mode':key_mode,'gamma_value':gamma,'smoothness':s,'smooth_range':r,'extra_smooth':e,'raw_sha256':hashlib.sha256(actual).hexdigest(),'class_plane_sha256':hashlib.sha256(plane).hexdigest(),'classifier_instructions':ci,'worker_instructions':wi,'padding_per_row':pad,'exact':True})
  req(len(rows)==18,'case count');report={'schema':'olmsmoother2.palette-ownership-covering/1','verdict':'PASS_18_PALETTE_OWNERSHIP_GAMMA_KEY_SMOOTHING_ALL_DEPTHS_EXACT','scope':'six covering tuples x PF8/PF16/PF32 on padded 9x7 diagonal fixture','case_count':len(rows),'tuples':[{'name':x[0],'palette_count':x[1],'palette_rgba':x[2][:x[1]],'key_mode':x[3],'gamma_value':x[4],'smoothing':[x[5],x[6],x[7]]} for x in TUPLES],'cases':rows,'controls':'olmsmoother2_gamma_key_smoothing_crossproduct_actual_aex_20260812 (54/54 default two-entry palette)','aex_sha256':base.typed.AEX_SHA256,'production_source_sha256':hashlib.sha256(SOURCE.read_bytes()).hexdigest(),'claims_not_made':['No arbitrary palette colors/order/count combinations','No arbitrary cross-product generalization','No AE-host execution claim']};REPORT.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');DOC.write_text('# OLMSmoother2 palette ownership covering matrix\n\nVerdict: `'+report['verdict']+'`\n\nSix covering tuples cross public palette counts 1/5, normal/reordered/duplicate ownership, Gamma Colors 1.0/2.4, key off/non-invert/invert, default/mixed smoothing, and PF8/PF16/PF32 on one padded 9x7 non-uniform fixture. All 18 actual-AEX owner/classifier/typed-worker outputs match production raw bytes exactly with padding preserved.\n\nThe prior 54-case two-entry palette matrix remains the control. Arbitrary palettes, arbitrary cross-products, and AE-host execution are not generalized.\n');print(report['verdict'],len(rows))
if __name__=='__main__':raise SystemExit(main())
