#!/usr/bin/env python3
"""Join production PF32 SmartRender public chain to actual AEX core and installed identity."""
from __future__ import annotations
import hashlib,json,subprocess,tempfile
from pathlib import Path
import test_olmsmoother2_v2_nonuniform_actual_aex_20260805 as v2
import test_olmsmoother2_typed_writeback_20260717 as typed
ROOT=Path(__file__).resolve().parents[2];HARNESS=ROOT/'tools/emulation/olmsmoother2_v2_effectmain_pf32_smart_production_harness_20260805.cpp';SOURCE=ROOT/'mac/OLMSmoother2/Mac/OLMSmoother2_port.cpp';INSTALLED=Path.home()/'Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/OLMSmoother2.plugin';BINARY=INSTALLED/'Contents/MacOS/OLMSmoother2';INSTALL=ROOT/'refs/conformance/olmsmoother2_mac_universal_install_boundary_20260805.json';REPORT=ROOT/'refs/conformance/olmsmoother2_effectmain_pf32_smart_chain_installed_20260805.json';DOC=ROOT/'refs/conformance/olmsmoother2_effectmain_pf32_smart_chain_installed_20260805.md'
def req(x,m):
 if not x:raise RuntimeError('FAIL CLOSED: '+m)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 ins=json.loads(INSTALL.read_text());req(BINARY.is_file(),'installed missing');ih=sha(BINARY);req(ih==ins['installation']['installed_binary_sha256'],'installed drift');arch=subprocess.run(['lipo','-archs',str(BINARY)],check=True,text=True,capture_output=True).stdout.split();req(set(arch)=={'x86_64','arm64'},'arch')
 with tempfile.TemporaryDirectory(prefix='sm2smart32_') as td:
  b=Path(td)/'h';subprocess.run(['clang++','-std=c++17','-O2','-I',str(ROOT/'cli/OLMSmoother2/shim'),'-I',str(ROOT/'mac/OLMSmoother2/Mac'),str(HARNESS),'-o',str(b)],check=True);lines=subprocess.run([str(b)],check=True,text=True,capture_output=True).stdout.splitlines()
 prod=lines[0].split()[1];calls=[int(x) for x in lines[1].split()[1:]];req(calls==[1,1,15,15],'callback counts');px=[(0,0,0,1),(0,1,1,1),(1,0,1,1),(1,1,0,1),(.25,.25,.25,1),(.75,.75,.75,1)];px=[tuple(typed.f32(v) for v in q) for q in px];raw,plane,linear,ci,wi=v2.actual('PF32',px,12);req(raw.hex()==prod,'PF32 SmartRender mismatch');report={'verdict':'PASS_PRODUCTION_EFFECTMAIN_SMARTRENDER_PF32_TO_ACTUAL_AEX_CORE_INSTALLED_IDENTITY','closed_boundary':'production EffectMain(PF_Cmd_SMART_RENDER) callback/parameter checkout -> PF32 RenderBits joined byte-exactly to actual AEX classifier/worker/writer','chain':['EffectMain PF_Cmd_SMART_RENDER','checkout_layer_pixels','checkout_output','15 ordered parameter checkouts','RenderBits<PF_PixelFloat>','15 parameter checkins','actual AEX natural classifier/PF32 worker/writer exact bytes','installed Universal identity'],'callback_counts':{'checkout_layer_pixels':1,'checkout_output':1,'parameter_checkout':15,'parameter_checkin':15},'actual_aex_sha256':typed.AEX_SHA256,'production_source_sha256':sha(SOURCE),'installed':{'path':str(INSTALLED),'binary_sha256':ih,'architectures':arch},'fixture':{'raw_hex':raw.hex(),'class_plane_hex':plane.hex(),'padding_preserved':True,'classifier_instructions':ci,'worker_instructions':wi},'remaining_largest_boundary':'actual-AEX exported entry invocation and real AE host load/command binding','claims_not_made':['No AE host execution','No actual-AEX exported entry invocation','No SmartPreRender in this report']};REPORT.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');DOC.write_text('# OLMSmoother2 PF32 SmartRender-to-installed chain\n\nVerdict: `'+report['verdict']+'`\n\nProduction `EffectMain(PF_Cmd_SMART_RENDER)` executes layer/output checkout, all 15 parameter checkouts, PF32 RenderBits, and all checkins. Its padded bytes equal the natural actual-AEX classifier/PF32 worker/writer fixture and are bound to installed Universal SHA `'+ih+'`.\n\nActual-AEX exported entry invocation, SmartPreRender, and AE-host loading remain separate boundaries.\n');print(json.dumps(report,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
