"""Compile a witness-spec JSON document into a sendable Windows package."""

from __future__ import annotations

import argparse
import json
import shutil
from copy import deepcopy
from pathlib import Path
from typing import Any

from .core import canonical_json, deterministic_zip, load_spec, sha256_file


HERE = Path(__file__).resolve().parent
RUNTIME_FILES = {
    "artifacts/run_witness.ps1": HERE / "runtime" / "run_witness.ps1",
    "scripts/witness_runtime.py": HERE / "runtime.py",
}


def _queue_source(contract: dict[str, Any]) -> str:
    case_ids = json.dumps([case["id"] for case in contract["cases"]], ensure_ascii=True)
    environment = json.dumps(contract["project"].get("environment", {}), ensure_ascii=True, sort_keys=True)
    return f'''/* Generated serial AE witness queue. Common behavior; probes live in CDB templates. */
(function () {{
    function env(name) {{ try {{ return $.getenv(name) || ""; }} catch (_) {{ return ""; }} }}
    function write(path, value, append) {{
        var file = new File(path); file.encoding = "UTF-8";
        if (!file.open(append ? "a" : "w")) {{ throw new Error("could not write " + path); }}
        file.write(value); file.close();
    }}
    var bootstrapPath = File($.fileName).parent.fsName + "/queue_bootstrap.log";
    var work = env("WINDOWS_WITNESS_WORK_ROOT");
    var runId = env("WINDOWS_WITNESS_RUN_ID");
    var root = env("WINDOWS_WITNESS_PACKAGE_ROOT") || File($.fileName).parent.parent.fsName;
    root = new Folder(root).fsName;
    var queueSha256 = env("WINDOWS_WITNESS_QUEUE_SHA256");
    var bootstrapTempPath = bootstrapPath + ".tmp";
    write(bootstrapTempPath, "WITNESS_QUEUE_BOOTSTRAP\\n" +
        "run_id=" + runId + "\\n" +
        "work=" + work + "\\n" +
        "root=" + root + "\\n" +
        "queue_sha256=" + queueSha256 + "\\n", false);
    if (!(new File(bootstrapTempPath)).rename("queue_bootstrap.log")) {{
        throw new Error("could not publish queue bootstrap marker");
    }}
    var requestDir = new Folder(root + "/request").fsName;
    var cases = {case_ids};
    var extraEnvironment = {environment};
    if (!work || !runId || !root || !queueSha256) {{ throw new Error("WINDOWS_WITNESS queue binding is required"); }}
    var queueLog = work + "/queue.log";
    write(queueLog, "WITNESS_QUEUE_START run_id=" + runId + "\\n", false);
    for (var i = 0; i < cases.length; i++) {{
        var caseId = cases[i];
        $.setenv("OLM_AE_REQUEST_DIR", requestDir);
        $.setenv("OLM_AE_CASE_ID", caseId);
        $.setenv("OLM_AE_OUTPUT_DIR", work + "/exports/" + caseId);
        $.setenv("OLM_AE_LOG_PATH", work + "/ae_" + caseId + ".log");
        $.setenv("OLM_AE_RESULT_JSON", work + "/ae_result_" + caseId + ".json");
        $.setenv("OLM_AE_READY_MARKER", work + "/ready_" + caseId + ".marker");
        $.setenv("OLM_AE_CONTINUE_MARKER", work + "/continue_" + caseId + ".marker");
        $.setenv("OLM_AE_KEEP_OPEN", i === cases.length - 1 ? "0" : "1");
        $.setenv("OLM_AE_FORCE_NEW_PROJECT", i === 0 ? "1" : "0");
        for (var key in extraEnvironment) {{
            if (extraEnvironment.hasOwnProperty(key)) {{ $.setenv(key, String(extraEnvironment[key])); }}
        }}
        write(queueLog, "WITNESS_CASE_START run_id=" + runId + " case_id=" + caseId + "\\n", true);
        $.evalFile(new File(root + "/scripts/renderer.jsx"));
        write(queueLog, "WITNESS_CASE_END run_id=" + runId + " case_id=" + caseId + "\\n", true);
    }}
    write(queueLog, "WITNESS_QUEUE_END run_id=" + runId + "\\n", true);
}}());
'''


def _package_readme(contract: dict[str, Any]) -> str:
    cases = ", ".join(f"`{case['id']}`" for case in contract["cases"])
    return f"""# {contract['request_id']} Windows Witness

This package was generated by `tools/windows_witness` contract version 1.
It runs {cases} serially in one fresh desktop After Effects process using the
hash-pinned `{contract['plugin']['module_filename']}` at
`{contract['project']['bits_per_channel']}bpc` with the Software renderer.

Run from an interactive Windows desktop PowerShell session:

```powershell
.\\artifacts\\run_witness.ps1
```

The launcher waits for each renderer to report `effect_loaded=1` and
`parameters_applied=1`, binds exactly one AE PID and loaded module base across
all cases, arms CDB, and only then releases the renderer. Success requires all
event cardinalities, required fields, identity constraints, render results,
and required exports in `witness-contract.json`. Every other outcome is
`exact_bind_failure`; a deterministic return ZIP is still produced with the
available diagnostics.

Runtime requirements: Windows PowerShell 5.1+, desktop After Effects, CDB, and
the Python 3 launcher `py -3`.
"""


def _normalized_contract(spec: dict[str, Any]) -> dict[str, Any]:
    contract = deepcopy(spec)
    contract["contract_kind"] = "windows_ae_cdb_witness_m0"
    contract["success_status"] = "answered"
    contract["failure_status"] = "exact_bind_failure"
    contract["queue"] = "scripts/ae_witness_queue.jsx"
    contract["renderer"]["package_path"] = "scripts/renderer.jsx"
    contract["request_assets"]["package_path"] = "request"
    for index, case in enumerate(contract["cases"]):
        case["order"] = index
        case["package_cdb_template"] = f"cdb/{index:03d}_{case['id']}.cdb.in"
    core_logs = [
        "afterfx_launcher_stdout.txt",
        "afterfx_launcher_stderr.txt",
        "afterfx_process_diagnostics.json",
        "afterfx_bootstrap.cdb",
        "afterfx_bootstrap_cdb_trace.txt",
        "afterfx_launch_wrapper.cmd",
        "launched_queue.jsx",
        "queue_bootstrap.log",
        "queue.log",
        "combined_cdb_trace.txt",
        "capture_diagnostics.json",
        "runtime_identity.json",
        "validation_status.json",
    ]
    for case in contract["cases"]:
        case_id = case["id"]
        core_logs.extend([
            f"ready_{case_id}.marker",
            f"continue_{case_id}.marker",
            f"probe_{case_id}.cdb",
            f"cdb_trace_{case_id}.txt",
            f"cdb_stdout_{case_id}.txt",
            f"cdb_stderr_{case_id}.txt",
            f"ae_{case_id}.log",
            f"ae_result_{case_id}.json",
        ])
    contract["return_bundle"]["include_logs"] = list(dict.fromkeys(core_logs + contract["return_bundle"].get("include_logs", [])))
    return contract


def compile_witness(spec_path: Path, output_dir: Path, zip_path: Path | None = None) -> tuple[Path, Path]:
    """Compile *spec_path* and return the package directory and deterministic ZIP."""

    spec_path = spec_path.resolve()
    spec = load_spec(spec_path)
    base = spec_path.parent
    output_dir = output_dir.resolve()
    archive = (zip_path.resolve() if zip_path else output_dir.with_suffix(".zip"))
    if output_dir == archive or output_dir in archive.parents:
        raise ValueError("zip path must be outside the package directory")

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)
    contract = _normalized_contract(spec)

    shutil.copytree(base / spec["request_assets"]["source"], output_dir / "request")
    (output_dir / "scripts").mkdir()
    (output_dir / "artifacts").mkdir()
    (output_dir / "cdb").mkdir()
    shutil.copy2(base / spec["renderer"]["source"], output_dir / "scripts" / "renderer.jsx")
    for destination, source in RUNTIME_FILES.items():
        shutil.copy2(source, output_dir / destination)
    (output_dir / "scripts" / "ae_witness_queue.jsx").write_text(_queue_source(contract), encoding="utf-8", newline="\n")
    (output_dir / "README.md").write_text(_package_readme(contract), encoding="utf-8", newline="\n")

    for case, compiled_case in zip(spec["cases"], contract["cases"]):
        source = base / case["cdb_template"]
        destination = output_dir / compiled_case["package_cdb_template"]
        destination.write_text(source.read_text(encoding="utf-8"), encoding="ascii", newline="\n")

    contract_path = output_dir / "witness-contract.json"
    contract_path.write_bytes(canonical_json(contract))
    inventory: list[dict[str, Any]] = []
    for path in sorted((path for path in output_dir.rglob("*") if path.is_file()), key=lambda item: item.relative_to(output_dir).as_posix()):
        inventory.append({
            "path": path.relative_to(output_dir).as_posix(),
            "sha256": sha256_file(path),
            "size_bytes": path.stat().st_size,
        })
    manifest = {
        "schema_version": 1,
        "kind": "windows_witness_generated_package",
        "request_id": spec["request_id"],
        "contract": "witness-contract.json",
        "entrypoint": "artifacts/run_witness.ps1",
        "files": inventory,
    }
    if "queue" in spec:
        manifest["queue"] = spec["queue"]
    (output_dir / "package-manifest.json").write_bytes(canonical_json(manifest))
    deterministic_zip(output_dir, archive)
    return output_dir, archive


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("spec", type=Path)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--zip", dest="zip_path", type=Path)
    args = parser.parse_args(argv)
    package, archive = compile_witness(args.spec, args.output_dir, args.zip_path)
    print(json.dumps({"status": "ok", "package": str(package), "zip": str(archive)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
