"""Compile a witness-spec JSON document into a sendable Windows package."""

from __future__ import annotations

import argparse
import json
import shutil
import re
from copy import deepcopy
from pathlib import Path
from typing import Any

from .core import SpecError, canonical_json, deterministic_zip, sha256_file, validate_spec


HERE = Path(__file__).resolve().parent
LEGACY_CDB_RUNTIME = (
    HERE.parents[1]
    / "refs/runtime_trace_packages/windows_witness_olmblur_case0006_20260713/artifacts/run_witness.ps1"
)
COLLECTOR_PLACEHOLDER_RE = re.compile(r"\{\{([^{}]+)\}\}")
COLLECTOR_STATIC_PLACEHOLDERS = {"RUN_ID", "AE_PID", "CASE_ID", "OUTPUT_DIR"}
RUNTIME_FILES = {
    "artifacts/run_witness.ps1": HERE / "runtime" / "run_witness.ps1",
    "scripts/witness_runtime.py": HERE / "runtime.py",
}


def _queue_source(contract: dict[str, Any]) -> str:
    case_ids = json.dumps([case["id"] for case in contract["cases"]], ensure_ascii=True)
    environment = json.dumps(contract["project"].get("environment", {}), ensure_ascii=True, sort_keys=True)
    return f'''/* Generated serial AE witness queue. Common behavior; probes live in CDB templates. */
(function () {{
    function env(name) {{ try {{ return $.getenv(name) || ""; }} catch (_) {{ return ""; }} }}
    function write(path, value, append) {{
        var file = new File(path); file.encoding = "UTF-8";
        if (!file.open(append ? "a" : "w")) {{ throw new Error("could not write " + path); }}
        file.write(value); file.close();
    }}
    function read(path) {{
        var file = new File(path); file.encoding = "UTF-8";
        if (!file.open("r")) {{ throw new Error("could not read " + path); }}
        var value = file.read(); file.close();
        return value;
    }}
    var bootstrapPath = File($.fileName).parent.fsName + "/queue_bootstrap.log";
    var work = env("WINDOWS_WITNESS_WORK_ROOT");
    var runId = env("WINDOWS_WITNESS_RUN_ID");
    var root = env("WINDOWS_WITNESS_PACKAGE_ROOT") || File($.fileName).parent.parent.fsName;
    root = new Folder(root).fsName;
    var queueSha256 = env("WINDOWS_WITNESS_QUEUE_SHA256");
    var bootstrapTempPath = bootstrapPath + ".tmp";
    write(bootstrapTempPath, "WITNESS_QUEUE_BOOTSTRAP\\n" +
        "run_id=" + runId + "\\n" +
        "work=" + work + "\\n" +
        "root=" + root + "\\n" +
        "queue_sha256=" + queueSha256 + "\\n", false);
    if (!(new File(bootstrapTempPath)).rename("queue_bootstrap.log")) {{
        throw new Error("could not publish queue bootstrap marker");
    }}
    var requestDir = new Folder(root + "/request").fsName;
    var cases = {case_ids};
    var extraEnvironment = {environment};
    var rendererSource = read(root + "/scripts/renderer.jsx");
    if (!work || !runId || !root || !queueSha256) {{ throw new Error("WINDOWS_WITNESS queue binding is required"); }}
    var queueLog = work + "/queue.log";
    write(queueLog, "WITNESS_QUEUE_START run_id=" + runId + "\\n", false);
    for (var i = 0; i < cases.length; i++) {{
        var caseId = cases[i];
        $.setenv("OLM_AE_REQUEST_DIR", requestDir);
        $.setenv("OLM_AE_CASE_ID", caseId);
        $.setenv("OLM_AE_OUTPUT_DIR", work + "/exports/" + caseId);
        $.setenv("OLM_AE_LOG_PATH", work + "/ae_" + caseId + ".log");
        $.setenv("OLM_AE_RESULT_JSON", work + "/ae_result_" + caseId + ".json");
        $.setenv("OLM_AE_READY_MARKER", work + "/ready_" + caseId + ".marker");
        $.setenv("OLM_AE_CONTINUE_MARKER", work + "/continue_" + caseId + ".marker");
        $.setenv("OLM_AE_KEEP_OPEN", i === cases.length - 1 ? "0" : "1");
        $.setenv("OLM_AE_FORCE_NEW_PROJECT", i === 0 ? "1" : "0");
        for (var key in extraEnvironment) {{
            if (extraEnvironment.hasOwnProperty(key)) {{ $.setenv(key, String(extraEnvironment[key])); }}
        }}
        write(queueLog, "WITNESS_CASE_START run_id=" + runId + " case_id=" + caseId + "\\n", true);
        // `-r` already owns AE's script slot. evalFile would be rejected as a
        // second script unless AE is launched with an override flag.
        eval(rendererSource);
        write(queueLog, "WITNESS_CASE_END run_id=" + runId + " case_id=" + caseId + "\\n", true);
    }}
    write(queueLog, "WITNESS_QUEUE_END run_id=" + runId + "\\n", true);
}}());
'''


def _package_readme(contract: dict[str, Any]) -> str:
    cases = ", ".join(f"`{case['id']}`" for case in contract["cases"])
    collector = contract.get("transport", {}).get("kind") == "in_process_collector"
    if not collector:
        return f"""# {contract['request_id']} Windows Witness

This package was generated by `tools/windows_witness` contract version 1.
It runs {cases} serially in one fresh desktop After Effects process using the
hash-pinned `{contract['plugin']['module_filename']}` at
`{contract['project']['bits_per_channel']}bpc` with the Software renderer.

Run from an interactive Windows desktop PowerShell session:

```powershell
.\\artifacts\\run_witness.ps1
```

The launcher waits for each renderer to report `effect_loaded=1` and
`parameters_applied=1`, binds exactly one AE PID and loaded module base across
all cases, arms CDB, and only then releases the renderer. Success requires all
event cardinalities, required fields, identity constraints, render results,
and required exports in `witness-contract.json`. Every other outcome is
`exact_bind_failure`; a deterministic return ZIP is still produced with the
available diagnostics.

Runtime requirements: Windows PowerShell 5.1+, desktop After Effects, CDB, and
the Python 3 launcher `py -3`.
"""
    transport_requirements = "the packaged injector and collector DLL" if collector else "CDB"
    capture_sentence = (
        "injects the configured collector into the exact AE PID and requires valid collector outputs"
        if collector else "arms CDB and only then releases the renderer"
    )
    return f"""# {contract['request_id']} Windows Witness

This package was generated by `tools/windows_witness` contract version 1.
It runs {cases} serially in one fresh desktop After Effects process using the
hash-pinned `{contract['plugin']['module_filename']}` at
`{contract['project']['bits_per_channel']}bpc` with the Software renderer.

Run from an interactive Windows desktop PowerShell session:

```powershell
.\\artifacts\\run_witness.ps1
```

The launcher waits for each renderer to report `effect_loaded=1` and
`parameters_applied=1`, binds exactly one AE PID and loaded module base across
all cases, {capture_sentence}. Success requires all
event cardinalities, required fields, identity constraints, render results,
and required exports in `witness-contract.json`. Every other outcome is
`exact_bind_failure`; a deterministic return ZIP is still produced with the
available diagnostics.

Runtime requirements: Windows PowerShell 5.1+, desktop After Effects,
{transport_requirements}, and the Python 3 launcher `py -3`.
"""


def _normalized_contract(spec: dict[str, Any]) -> dict[str, Any]:
    contract = deepcopy(spec)
    transport = spec.get("transport", {"kind": "cdb"})
    contract["contract_kind"] = (
        "windows_ae_collector_witness_m0"
        if transport["kind"] == "in_process_collector"
        else "windows_ae_cdb_witness_m0"
    )
    contract["success_status"] = "answered"
    contract["failure_status"] = "exact_bind_failure"
    contract["queue"] = "scripts/ae_witness_queue.jsx"
    contract["renderer"]["package_path"] = "scripts/renderer.jsx"
    contract["request_assets"]["package_path"] = "request"
    for index, case in enumerate(contract["cases"]):
        case["order"] = index
        if transport["kind"] == "cdb":
            case["package_cdb_template"] = f"cdb/{index:03d}_{case['id']}.cdb.in"
    core_logs = [
        "afterfx_launcher_stdout.txt",
        "afterfx_launcher_stderr.txt",
        "afterfx_process_diagnostics.json",
        "afterfx_bootstrap.cdb",
        "afterfx_bootstrap_cdb_trace.txt",
        "afterfx_launch_wrapper.cmd",
        "launched_queue.jsx",
        "queue_bootstrap.log",
        "queue.log",
        "combined_cdb_trace.txt",
        "capture_diagnostics.json",
        "runtime_identity.json",
        "validation_status.json",
    ]
    if contract["plugin"].get("cache_rescan") is True:
        core_logs.append("plugin_cache_rescan.json")
    for case in contract["cases"]:
        case_id = case["id"]
        core_logs.extend([
            f"ready_{case_id}.marker",
            f"continue_{case_id}.marker",
        ])
        if transport["kind"] == "cdb":
            core_logs.extend([
                f"probe_{case_id}.cdb", f"cdb_trace_{case_id}.txt",
                f"cdb_stdout_{case_id}.txt", f"cdb_stderr_{case_id}.txt",
            ])
        else:
            for output in transport["required_outputs"]:
                core_logs.append(f"collector_{case_id}_{Path(output).name}")
            core_logs.append(f"collector_config_{case_id}.json")
            core_logs.extend([f"collector_stdout_{case_id}.txt", f"collector_stderr_{case_id}.txt"])
        core_logs.extend([f"ae_{case_id}.log", f"ae_result_{case_id}.json"])
    if transport["kind"] == "in_process_collector":
        contract["transport"] = dict(transport)
        contract["transport"].update({
            "package_injector_path": "collector/injector.exe",
            "package_collector_dll": "collector/collector.dll",
            "package_config_template": "collector/config.json.in",
            "arm_timeout_seconds": int(transport.get("arm_timeout_seconds", 30)),
            "capture_timeout_seconds": int(transport.get("capture_timeout_seconds", 60)),
        })
    contract["return_bundle"]["include_logs"] = list(dict.fromkeys(core_logs + contract["return_bundle"].get("include_logs", [])))
    return contract


def compile_witness(spec_path: Path, output_dir: Path, zip_path: Path | None = None) -> tuple[Path, Path]:
    """Compile *spec_path* and return the package directory and deterministic ZIP."""

    spec_path = spec_path.resolve()
    spec = _load_spec_for_compiler(spec_path)
    base = spec_path.parent
    output_dir = output_dir.resolve()
    archive = (zip_path.resolve() if zip_path else output_dir.with_suffix(".zip"))
    if output_dir == archive or output_dir in archive.parents:
        raise ValueError("zip path must be outside the package directory")

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)
    contract = _normalized_contract(spec)
    transport = spec.get("transport", {"kind": "cdb"})

    shutil.copytree(base / spec["request_assets"]["source"], output_dir / "request")
    (output_dir / "scripts").mkdir()
    (output_dir / "artifacts").mkdir()
    (output_dir / "cdb").mkdir()
    shutil.copy2(base / spec["renderer"]["source"], output_dir / "scripts" / "renderer.jsx")
    for destination, source in RUNTIME_FILES.items():
        if destination == "artifacts/run_witness.ps1" and transport.get("kind", "cdb") == "cdb":
            (output_dir / destination).write_bytes(_legacy_cdb_runtime(source))
        else:
            shutil.copy2(source, output_dir / destination)
    (output_dir / "scripts" / "ae_witness_queue.jsx").write_text(_queue_source(contract), encoding="utf-8", newline="\n")
    (output_dir / "README.md").write_text(_package_readme(contract), encoding="utf-8", newline="\n")

    if transport["kind"] == "cdb":
        for case, compiled_case in zip(spec["cases"], contract["cases"]):
            source = base / case["cdb_template"]
            destination = output_dir / compiled_case["package_cdb_template"]
            destination.write_text(source.read_text(encoding="utf-8"), encoding="ascii", newline="\n")
    else:
        for source_key, destination_name in (
            ("injector_path", "collector/injector.exe"),
            ("collector_dll", "collector/collector.dll"),
            ("config_template", "collector/config.json.in"),
        ):
            source = base / transport[source_key]
            destination = output_dir / destination_name
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)

    contract_path = output_dir / "witness-contract.json"
    contract_path.write_bytes(canonical_json(contract))
    inventory: list[dict[str, Any]] = []
    for path in sorted((path for path in output_dir.rglob("*") if path.is_file()), key=lambda item: item.relative_to(output_dir).as_posix()):
        inventory.append({
            "path": path.relative_to(output_dir).as_posix(),
            "sha256": sha256_file(path),
            "size_bytes": path.stat().st_size,
        })
    manifest = {
        "schema_version": 1,
        "kind": "windows_witness_generated_package",
        "request_id": spec["request_id"],
        "contract": "witness-contract.json",
        "entrypoint": "artifacts/run_witness.ps1",
        "files": inventory,
    }
    if "queue" in spec:
        manifest["queue"] = spec["queue"]
    (output_dir / "package-manifest.json").write_bytes(canonical_json(manifest))
    deterministic_zip(output_dir, archive)
    return output_dir, archive


def _legacy_cdb_runtime(source: Path) -> bytes:
    """Keep the pre-transport CDB artifact byte-identical for existing packages."""
    if not LEGACY_CDB_RUNTIME.is_file():
        raise SpecError(f"canonical legacy CDB runtime is missing: {LEGACY_CDB_RUNTIME}")
    return LEGACY_CDB_RUNTIME.read_bytes()


def _load_spec_for_compiler(spec_path: Path) -> dict[str, Any]:
    """Load legacy specs through the original validator and collector specs through its shared rules."""
    try:
        raw = json.loads(spec_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SpecError(f"could not read spec {spec_path}: {exc}") from exc
    _validate_plugin_cache_rescan(raw)
    transport = raw.get("transport", {"kind": "cdb"})
    compatibility = deepcopy(raw)
    compatibility.get("plugin", {}).pop("cache_rescan", None)
    if not isinstance(transport, dict) or transport.get("kind") == "cdb":
        validate_spec(compatibility, spec_path.parent)
        return raw
    if transport.get("kind") != "in_process_collector":
        raise SpecError("transport.kind must be cdb or in_process_collector")
    compatibility.pop("transport", None)
    compatibility.setdefault("host", {}).setdefault("cdb_path", "collector-compat-cdb.exe")
    compatibility["cdb"] = {"armed_marker": "collector_compat", "arm_timeout_seconds": 1, "capture_timeout_seconds": 1}
    for case in compatibility.get("cases", []):
        case.setdefault("cdb_template", "collector_compat.cdb.in")
    validate_spec(compatibility, None)
    _validate_collector_transport(raw, spec_path.parent)
    return raw


def _validate_plugin_cache_rescan(spec: dict[str, Any]) -> None:
    plugin = spec.get("plugin")
    if not isinstance(plugin, dict):
        raise SpecError("plugin must be an object")
    if "cache_rescan" in plugin and type(plugin["cache_rescan"]) is not bool:
        raise SpecError("plugin.cache_rescan must be boolean")


def _validate_collector_transport(spec: dict[str, Any], base: Path) -> None:
    transport = spec.get("transport")
    if not isinstance(transport, dict):
        raise SpecError("spec.transport must be an object")
    allowed = {"kind", "injector_path", "collector_dll", "config_template", "required_outputs", "arm_timeout_seconds", "capture_timeout_seconds"}
    extra = set(transport) - allowed
    if extra:
        raise SpecError(f"spec.transport has unknown keys: {', '.join(sorted(extra))}")
    required = {"kind", "injector_path", "collector_dll", "config_template", "required_outputs"}
    missing = required - set(transport)
    if missing:
        raise SpecError(f"spec.transport missing keys: {', '.join(sorted(missing))}")
    for key in ("injector_path", "collector_dll", "config_template"):
        value = transport[key]
        if not isinstance(value, str) or not value or value.startswith(("/", "\\")) or ".." in Path(value).parts:
            raise SpecError(f"spec.transport.{key} must be a safe relative path")
        path = base / value
        if not path.is_file():
            raise SpecError(f"missing collector asset: {path}")
    outputs = transport["required_outputs"]
    if not isinstance(outputs, list) or not outputs or any(not isinstance(output, str) for output in outputs) or len(outputs) != len(set(outputs)):
        raise SpecError("spec.transport.required_outputs must be a non-empty unique array")
    for output in outputs:
        if not isinstance(output, str) or not output or output.startswith(("/", "\\")) or ".." in Path(output).parts:
            raise SpecError("spec.transport.required_outputs must contain safe relative paths")
    if not {"collector_trace.txt", "collector_status.json"}.issubset(outputs):
        raise SpecError("spec.transport.required_outputs must include collector_trace.txt and collector_status.json")
    basenames = [Path(output).name for output in outputs]
    if len(basenames) != len(set(basenames)):
        raise SpecError("spec.transport.required_outputs must have unique basenames")
    for key in ("arm_timeout_seconds", "capture_timeout_seconds"):
        timeout = transport.get(key, 30 if key == "arm_timeout_seconds" else 60)
        if type(timeout) is not int or timeout < 1:
            raise SpecError(f"spec.transport.{key} must be a positive integer")
    template = (base / transport["config_template"]).read_text(encoding="utf-8")
    placeholders = set(COLLECTOR_PLACEHOLDER_RE.findall(template))
    for placeholder in placeholders:
        if placeholder in COLLECTOR_STATIC_PLACEHOLDERS:
            continue
        if placeholder.startswith("CASE_VALUE:") and all(placeholder[11:] in case.get("template_values", {}) for case in spec["cases"]):
            continue
        raise SpecError(f"collector config has unsupported or unresolved placeholder {{{{{placeholder}}}}}")
    renderer = base / spec["renderer"]["source"]
    assets = base / spec["request_assets"]["source"]
    if not renderer.is_file():
        raise SpecError(f"missing renderer source: {renderer}")
    if not assets.is_dir():
        raise SpecError(f"missing request assets: {assets}")
    manifest = assets / "request_manifest.json"
    if manifest.is_file():
        try:
            embedded = json.loads(manifest.read_text(encoding="utf-8-sig"))
        except (OSError, json.JSONDecodeError) as exc:
            raise SpecError(f"could not read embedded request manifest {manifest}: {exc}") from exc
        if not isinstance(embedded, dict) or embedded.get("request_id") != spec.get("request_id"):
            raise SpecError(f"{manifest} request_id must exactly match spec.request_id")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("spec", type=Path)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--zip", dest="zip_path", type=Path)
    args = parser.parse_args(argv)
    package, archive = compile_witness(args.spec, args.output_dir, args.zip_path)
    print(json.dumps({"status": "ok", "package": str(package), "zip": str(archive)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
