#!/usr/bin/env python3
"""Smoke-test the OLMBlur case_0006 same-run internal package."""

from __future__ import annotations

import json
import hashlib
import re
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PACKAGE = ROOT / "refs/runtime_trace_packages/olm_runtime_trace_olmblur_case0006_same_run_internal_20260713"
ZIP = PACKAGE.with_suffix(".zip")
HASH = "f0611785e7b14ac4fcfc75f23b8862beb4539eee52d25d472556849535e96e5b"
SCHEMA = "olmblur-case0006-same-run-internal-return-v1"
CASE_ID = "olmblur__case_0006"
CLASSIFIER = ROOT / "scripts/classify_olmblur_case0006_same_run_internal_return.py"
POINTS = {(29, 71): "capture", (314, 14): "control"}


def classify(path: Path) -> bool:
    rows: dict[str, list[dict[str, str]]] = {"WORKER_ENTRY": [], "FINAL_PRE_STORE": [], "STORED_RGB16": []}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^BLUR16_(WORKER_ENTRY|FINAL_PRE_STORE|STORED_RGB16)\s+", line)
        if match: rows[match.group(1)].append(dict(re.findall(r"([a-z0-9_]+)=([^\s]+)", line)))
    if len(rows["WORKER_ENTRY"]) != 1 or len(rows["FINAL_PRE_STORE"]) != 2 or len(rows["STORED_RGB16"]) != 2: return False
    all_rows = sum(rows.values(), [])
    for field, expected in (("aex_sha256", HASH), ("project_bpc", "16"), ("renderer", "Software"), ("case_id", CASE_ID)):
        if {row.get(field) for row in all_rows} != {expected}: return False
    for field in ("run_id", "ae_pid", "module_base"):
        if len({row.get(field) for row in all_rows}) != 1: return False
    if rows["WORKER_ENTRY"][0].get("entry_rva") != "2280": return False
    for stage in ("FINAL_PRE_STORE", "STORED_RGB16"):
        seen = set()
        for row in rows[stage]:
            point = (int(row["x"]), int(row["y"])); seen.add(point)
            if POINTS.get(point) != row.get("role") or row.get("output_addr") != row.get("expected_output_addr"): return False
        if seen != set(POINTS): return False
    return True


def fail(message: str) -> int:
    print(f"[FAIL] {message}"); return 1


def main() -> int:
    required = {"README_RUNTIME_TRACE.md", "runtime_trace_package_manifest.json", "RETURN_RUNTIME_TRACE_TEMPLATE.json", "artifacts/run_olmblur_case0006_same_run_internal_20260713.ps1", "scripts/ae_render_olmblur_case0006_queue.jsx", "scripts/ae_render_single_case.jsx", "scripts/inspect_png16.py", "request/request_manifest.json", "request/reference_manifest.json", "request/input/case_0006_before_effects.png", "fixtures/complete_cdb_trace.txt", "fixtures/missing_stage_cdb_trace.txt", "fixtures/identity_drift_cdb_trace.txt", "fixtures/role_drift_cdb_trace.txt"}
    if not PACKAGE.is_dir() or not ZIP.is_file(): return fail("package directory or ZIP missing")
    files = {p.relative_to(PACKAGE).as_posix() for p in PACKAGE.rglob("*") if p.is_file()}
    if not required <= files: return fail(f"missing package files: {sorted(required-files)}")
    for path in PACKAGE.rglob("*"):
        if path.is_dir() and path.name == "__pycache__": return fail("generated bytecode directory leaked")
        if not path.is_file(): continue
        data = path.read_bytes()
        if path.suffix == ".pyc" or b"/Users/" in data or b"C:\\Users\\" in data:
            return fail(f"workstation absolute path leaked: {path.relative_to(PACKAGE)}")
    with zipfile.ZipFile(ZIP) as archive:
        names = {n for n in archive.namelist() if not n.endswith("/")}
        if names != files: return fail("ZIP and package directory differ")
        if any(i.date_time != (2026, 7, 13, 0, 0, 0) for i in archive.infolist() if not i.is_dir()): return fail("ZIP timestamps are nondeterministic")
        manifest = json.loads(archive.read("runtime_trace_package_manifest.json")); request = json.loads(archive.read("request/request_manifest.json")); reference = json.loads(archive.read("request/reference_manifest.json")); template = json.loads(archive.read("RETURN_RUNTIME_TRACE_TEMPLATE.json"))
    if not manifest.get("sendable") or manifest["plugin"]["required_sha256"] != HASH: return fail("manifest is not hash-pinned/sendable")
    if manifest["render"] != {"case_id": CASE_ID, "bits_per_channel": 16, "renderer": "Software", "output": "PNG16"}: return fail("render contract drifted")
    if [c["id"] for c in request["cases"]] != [CASE_ID] or [c["id"] for c in reference["cases"]] != [CASE_ID]: return fail("request is not narrow")
    if template.get("schema") != SCHEMA or template.get("case_id") != CASE_ID or template.get("run", {}).get("project_depth") != 16:
        return fail("return template does not match classifier schema/depth")
    if set(template.get("exported_png", {})) < {"archive_path", "png_sha256", "png_size_bytes", "witnesses"}:
        return fail("return template exported_png contract is incomplete")
    if not classify(PACKAGE / "fixtures/complete_cdb_trace.txt"): return fail("complete fixture rejected")
    for name in ("missing_stage_cdb_trace.txt", "identity_drift_cdb_trace.txt", "role_drift_cdb_trace.txt"):
        if classify(PACKAGE / "fixtures" / name): return fail(f"adversarial fixture accepted: {name}")
    runner = (PACKAGE / "artifacts/run_olmblur_case0006_same_run_internal_20260713.ps1").read_text(encoding="utf-8")
    for term in ("Get-CimInstance Win32_Process", "SessionId", "Get-FileHash", "effect_loaded=1", "parameters_applied=1", "Start-Process -FilePath $AfterFxPath", "Start-Process -FilePath $CdbPath", "0x2280", "0x2ff1", "0x3032", "BLUR16_WORKER_ENTRY", "BLUR16_FINAL_PRE_STORE", "BLUR16_STORED_RGB16", "Inspect-Png", "RETURN_OLMBLUR_CASE0006.json", "RETURN_OLMBLUR_CASE0006.zip", "return/exported_case_0006.png", "exact_bind_failure", "RawLogs"):
        if term not in runner: return fail(f"runner missing: {term}")
    if "$aeArgs=('-m -r \"' + $queue + '\"')" not in runner:
        return fail("AfterFX JSX arguments are not passed as one quoted string")
    if "-ArgumentList @('-m','-r',$queue)" in runner:
        return fail("known-broken split AfterFX argument form remains")
    if '.logopen /t "$trace"' not in runner:
        return fail("CDB trace is not opened with truncation")
    if runner.find("BLUR16_TYPED_BREAKPOINTS_ARMED_AFTER_WORKER_ENTRY") < runner.find("BLUR16_WORKER_ENTRY"): return fail("typed hooks are not entry-gated")
    queue = (PACKAGE / "scripts/ae_render_olmblur_case0006_queue.jsx").read_text(encoding="utf-8")
    for term in ("OLM_BLUR16_RUN_ID", "OLM_AE_READY_MARKER", "OLM_AE_CONTINUE_MARKER", "case_0006"):
        if term not in queue: return fail(f"queue missing: {term}")
    for path in (ROOT / "scripts/package_olmblur_case0006_same_run_internal_20260713.py", PACKAGE / "scripts/inspect_png16.py"):
        compile(path.read_text(encoding="utf-8"), path.name, "exec")
    inspected = subprocess.run(
        [sys.executable, str(PACKAGE / "scripts/inspect_png16.py"), "--input", str(PACKAGE / "request/input/case_0006_before_effects.png"), "--point", "29,71,capture", "--point", "314,14,control"],
        check=True, text=True, stdout=subprocess.PIPE,
    )
    png = json.loads(inspected.stdout)
    if png["width"] != 1920 or png["height"] != 1080 or png["bit_depth"] != 16 or len(png["points"]) != 2:
        return fail("bundled PNG16 inspector rejected the real case asset")
    identity = {"run_id": "synthetic-package-smoke", "ae_pid": 6106, "module": "OLMBlur.aex", "module_base": "0x7ff800000000", "aex_sha256": HASH, "project_depth": 16}
    witnesses = [
        {**identity, "xy": [29, 71], "pre_store_rgb_bits_hex": ["0x4435beb4"] * 3, "stored_rgb16": [727] * 3},
        {**identity, "xy": [314, 14], "pre_store_rgb_bits_hex": ["0x45098f32"] * 3, "stored_rgb16": [2201] * 3},
    ]
    png_path = PACKAGE / "request/input/case_0006_before_effects.png"; png_bytes = png_path.read_bytes()
    export_witnesses = [{**identity, "xy": [row["x"], row["y"]], "rgba16": row["rgba16"]} for row in png["points"]]
    payload = {"schema": SCHEMA, "status": "answered", "case_id": CASE_ID, "run": identity, "witnesses": witnesses,
               "exported_png": {**identity, "archive_path": "return/exported_case_0006.png", "png_sha256": hashlib.sha256(png_bytes).hexdigest(), "png_size_bytes": len(png_bytes), "witnesses": export_witnesses}}
    with tempfile.TemporaryDirectory(prefix="olmblur_package_return_") as tmp:
        synthetic = Path(tmp) / "RETURN_OLMBLUR_CASE0006.zip"
        with zipfile.ZipFile(synthetic, "w") as archive:
            archive.writestr("RETURN_OLMBLUR_CASE0006.json", json.dumps(payload))
            archive.writestr("return/exported_case_0006.png", png_bytes)
        subprocess.run([sys.executable, str(CLASSIFIER), str(synthetic)], cwd=ROOT, check=True, stdout=subprocess.PIPE, text=True)
    print("[OK] OLMBlur case_0006 same-run internal package is sendable and fail-closed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
