#!/usr/bin/env python3
"""Read-only readiness audit for current OLMSmoother2 Mac AE host phase."""
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];EXPECTED='fe782f344dcaf8865b778198b0faeb8cecd525062a83f38aca8dc1db74442c34';PLUGIN=Path.home()/'Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/OLMSmoother2.plugin';BINARY=PLUGIN/'Contents/MacOS/OLMSmoother2';RUNNER=ROOT/'scripts/run_olmsmoother2_no_key_32bpc_mac_validation_20260715.py';ATTESTOR=ROOT/'scripts/attest_olmsmoother2_mac_process_20260728.py';PF32=ROOT/'refs/fixtures/olmsmoother2_32bpc_preserve_rgb_input_template_20260726.aep';PF16=ROOT/'refs/fixtures/olmsmoother2_case07_preserve_rgb_effect_20260727.aep';REPORT=ROOT/'refs/conformance/olmsmoother2_current_ae_host_preflight_20260805.json';DOC=ROOT/'refs/conformance/olmsmoother2_current_ae_host_preflight_20260805.md'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def req(x,m):
 if not x:raise RuntimeError('FAIL_CLOSED: '+m)
def main():
 req(BINARY.is_file(),'installed binary missing');req(sha(BINARY)==EXPECTED,'installed hash drift');arch=subprocess.run(['lipo','-archs',str(BINARY)],check=True,text=True,capture_output=True).stdout.split();req(set(arch)=={'x86_64','arm64'},'architectures');subprocess.run(['codesign','--verify','--deep','--strict',str(PLUGIN)],check=True)
 r=RUNNER.read_text();tokens=['EXPECTED_PLUGIN_SHA256 = "'+EXPECTED+'"','process_challenge','pre_snapshot','vmmap_match_count','bitsPerChannel=32','GpuAccelType.SOFTWARE','parameter readback'];missing=[x for x in tokens if x not in r];req(not missing,'runner tokens '+repr(missing));req(ATTESTOR.is_file(),'attestor missing');req(PF32.is_file() and sha(PF32)=='51fd5403b0a43825f0f6d189c49154ad756f4c565498f733c1fb725377583679','PF32 template drift');req(PF16.is_file() and sha(PF16)=='689da9c07512f821c869e0e17031db3d05953896e50b6b2385762f26afcf2f0d','PF16 fixture drift')
 ae_pids=subprocess.run(['pgrep','-f','Adobe After Effects 2026.app/Contents/MacOS/After Effects'],text=True,capture_output=True).stdout.split();report={'status':'ready_not_executed','installed':{'bundle':str(PLUGIN),'binary_sha256':EXPECTED,'architectures':arch,'codesign_verify':'pass'},'host_contract':{'renderer':'SOFTWARE','loaded_identity_gate':'attestor requires canonical installed path, SHA-256, one vmmap mapping, stable PID/birth token before and after render','expected_loaded_sha256':EXPECTED},'targets':{'PF16_classic':{'supported_core_chain':'EffectMain PF_Cmd_RENDER -> PF16 RenderBits','fixture':str(PF16.relative_to(ROOT)),'fixture_sha256':sha(PF16),'host_runner_status':'fixture and core chain pinned; dedicated current-hash PF16 host runner still separate'},'PF32_smart':{'supported_core_chain':'EffectMain PF_Cmd_SMART_RENDER -> PF32 RenderBits','runner':str(RUNNER.relative_to(ROOT)),'runner_sha256':sha(RUNNER),'project_template':str(PF32.relative_to(ROOT)),'project_template_sha256':sha(PF32),'attestor':str(ATTESTOR.relative_to(ROOT)),'host_runner_status':'ready'}},'ae_process_observation':{'matching_pids':ae_pids,'operation_performed':False},'execution':{'performed':False,'reason':'preflight-only task; AE launch/operation forbidden'},'next_action':'When authorized, run the PF32 runner with --plugin-path set to the pinned installed bundle, start its attestor, then launch/run the generated wrapper in a fresh AE Software session. PF16 needs a dedicated current-hash runner before host execution.'};REPORT.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');DOC.write_text('# OLMSmoother2 current AE host preflight\n\nStatus: `ready_not_executed`\n\nInstalled Universal SHA `'+EXPECTED+'` is present, codesign-valid, and `x86_64 + arm64`. The PF32 Software runner is pinned to that hash and its Preserve-RGB template. Its attestor requires one canonical loaded mapping plus stable process birth identity before and after rendering.\n\nPF16 classic is supported by the completed EffectMain chain and a hash-pinned AEP fixture, but still needs a dedicated current-hash host runner. No AE process was launched or operated.\n');print(json.dumps(report,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
