#!/usr/bin/env python3
"""Run the hash-bound PF16 fixture-source -> ColorKeep AE chain."""
from __future__ import annotations
import argparse, hashlib, importlib.util, json, plistlib, struct, subprocess, tempfile, time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];APP=Path("/Applications/Adobe After Effects 2026/Adobe After Effects 2026.app")
CK=Path.home()/"Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/ColorKeep.plugin/Contents/MacOS/ColorKeep";SRC=Path.home()/"Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/OLMPF16FixtureSource.plugin/Contents/MacOS/OLMPF16FixtureSource"
CK_SHA="ccc89781fa547450acc3053cb77bff8d6983cd8c6835866c87449e7a64117cce";SRC_SHA="ca098f4309c53d50eb16c67ecadde777c1ac2d29024d03103d46ea6d030b65b8"
PF16=((32768,32768,32768,32768),(32768,8192,24576,32768),(32768,0,0,0),(32768,32769,32768,32768),(32768,32768,32769,32768),(32768,32768,32768,32769),(32768,65535,65535,65535),(32769,32768,32768,32768),(65535,8192,24576,32768),(16384,65535,32769,49152),(1,32769,1,65535),(32768,12345,23456,34567))
EXPECTED_A=(32768,32768,32768,0,0,0,0,0,0,0,0,0)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def pids():
 r=subprocess.run(["pgrep","-f","^/Applications/Adobe After Effects 2026/Adobe After Effects 2026.app/Contents/MacOS/After Effects$"],capture_output=True,text=True);return [int(x) for x in r.stdout.split()]
def mapped(pid,path):
 r=subprocess.run(["vmmap",str(pid)],capture_output=True,text=True,timeout=120);return r.returncode==0 and any(str(path.resolve()) in x for x in r.stdout.splitlines())
def jsx(out,result,error):
 return r'''(function(){function F(m){throw new Error("FAIL_CLOSED: "+m)}function Q(v){return '"'+String(v).replace(/\\/g,"\\\\").replace(/"/g,'\\"')+'"'}function W(p,s){var f=new File(p);f.encoding="UTF-8";if(!f.open("w"))F("write");f.write(s);f.close()}function H(p){var x=system.callSystem("/usr/bin/shasum -a 256 '"+p.replace(/'/g,"'\\''")+"'"),m=x.match(/^([0-9a-f]{64})/);if(!m)F("hash");return m[1]}function R(c,ck,on,n){ck.enabled=on;var q=app.project.renderQueue.items.add(c),om=q.outputModule(1),p=OUT+"/"+n+".exr";om.applyTemplate("OLM EXR 32 Float");om.file=new File(p);app.project.renderQueue.render();var f=new File(p),a=f.parent.getFiles(f.name+"*");if(!f.exists){if(a.length!==1)F("output "+a.length);f=a[0]}q.remove();return{path:f.fsName,sha256:H(f.fsName)}}try{if(app.project)try{app.project.close(CloseOptions.DO_NOT_SAVE_CHANGES)}catch(_close){}var p=app.newProject();p.bitsPerChannel=16;p.workingSpace="";p.linearBlending=false;p.gpuAccelType=GpuAccelType.SOFTWARE;var c=p.items.addComp("ck_pf16_upstream",4,4,1,1,1),s=c.layers.addSolid([0,0,0],"fixture carrier",4,4,1,1),e=s.property("ADBE Effect Parade"),src=e.addProperty("OLM PF16 Fixture Source");if(!src||src.matchName!=="OLM Test PF16 Fixture Source")F("source missing/mismatch "+(src?src.matchName:"null"));var ck=e.addProperty("OLM Color Keep");if(!ck)F("ColorKeep missing");ck.property(1).setValue(3);var keys=[[1,1,1],[.25,.75,1],[0,0,0]],rb=[];for(var i=0;i<3;i++){ck.property(i+2).setValue(keys[i]);rb.push(ck.property(i+2).value)}var control=R(c,ck,false,"source_only"),chain=R(c,ck,true,"source_colorkeep");W(RESULT,JSON.stringify({status:"candidate_return_only",ae_exact_claim:false,ae_version:app.version,bpc:p.bitsPerChannel,readback:rb,outputs:{source_only:control,source_colorkeep:chain},hashes:{source:H(SRC),colorkeep:H(CK)}}));p.close(CloseOptions.DO_NOT_SAVE_CHANGES)}catch(e){W(ERROR,String(e)+" line="+String(e.line||""))}})();'''.replace("OUT",json.dumps(str(out))).replace("RESULT",json.dumps(str(result))).replace("ERROR",json.dumps(str(error))).replace("SRC",json.dumps(str(SRC))).replace("CK",json.dumps(str(CK)))
def planes(path):
 spec=importlib.util.spec_from_file_location("cmp",ROOT/"scripts/compare_float_exr.py");m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m.read_planes(path)
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--support-dir",type=Path,default=ROOT/"refs/mac_validation_runs/colorkeep_pf16_upstream_chain_20260806");a=ap.parse_args();a.support_dir=a.support_dir.resolve();a.support_dir.mkdir(parents=True,exist_ok=True);out=a.support_dir/"output";out.mkdir(exist_ok=True);result=a.support_dir/"candidate_return.json";error=a.support_dir/"error.log";script=a.support_dir/"run.jsx";script.write_text(jsx(out,result,error))
 if sha(CK)!=CK_SHA or sha(SRC)!=SRC_SHA:raise SystemExit("identity mismatch")
 subprocess.run(["open","-a",str(APP)],check=True);deadline=time.time()+120
 while time.time()<deadline and len(pids())!=1:time.sleep(1)
 pid=pids()[0];cmd='with timeout of 7200 seconds\ntell application "Adobe After Effects 2026" to DoScriptFile POSIX file '+json.dumps(str(script.resolve()))+' with override\nend timeout\n';run=subprocess.run(["osascript"],input=cmd,text=True,capture_output=True,timeout=7200)
 if run.returncode or not result.is_file():raise SystemExit(error.read_text() if error.exists() else run.stderr)
 if not mapped(pid,SRC) or not mapped(pid,CK):raise SystemExit("mapping failure")
 d=json.loads(result.read_text());sp,w,h=planes(Path(d["outputs"]["source_only"]["path"]));cp,_,_=planes(Path(d["outputs"]["source_colorkeep"]["path"]));source_a=[struct.unpack_from("<f",sp["A"],i*4)[0] for i in range(12)];chain_a=[struct.unpack_from("<f",cp["A"],i*4)[0] for i in range(12)];source_rgb=[struct.unpack_from("<f",sp[c],i*4)[0] for c in ("R","G","B") for i in range(12)];expected_source=[x[0]/32768 for x in PF16];expected_chain=[x/32768 for x in EXPECTED_A];d.update({"status":"host_chain_alpha_discriminator_exact" if source_a==expected_source and chain_a==expected_chain else "host_chain_alpha_mismatch","loaded_mapping":{"pid":pid,"source":True,"colorkeep":True},"source_only_alpha":source_a,"source_only_expected_output_conversion":expected_source,"chain_alpha":chain_a,"chain_expected_actual_aex":expected_chain,"inter_effect_extended_pf16_proven":source_a!=chain_a and chain_a==expected_chain,"output_rgb_extended_observable":any(x>1 for x in source_rgb)});result.write_text(json.dumps(d,indent=2,sort_keys=True)+"\n");print(json.dumps(d,indent=2));return 0 if d["status"].endswith("exact") else 1
if __name__=="__main__":raise SystemExit(main())
