param([string]$PackageRoot=$PSScriptRoot,[string]$AfterFX='C:\Program Files\Adobe\Adobe After Effects 2025\Support Files\AfterFX.exe',[string]$OutputTemplate='OLM EXR 32 Float',[int]$TimeoutSeconds=900)
$ErrorActionPreference='Stop'
function Fail([string]$m){throw "[FAIL_CLOSED] $m"};function Hash([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()};function Json([string]$p,$v){$v|ConvertTo-Json -Depth 100 -Compress|Set-Content -LiteralPath $p -Encoding UTF8}
function WaitFile([string]$p){$d=(Get-Date).AddSeconds($TimeoutSeconds);while((Get-Date)-lt$d){if(Test-Path -LiteralPath $p -PathType Leaf){return};Start-Sleep -Milliseconds 200};Fail "timeout $p"}
function StopOwnedAE([int]$id){if($id-le0){return};$p=Get-Process -Id $id -ErrorAction SilentlyContinue;if($p){$p|Stop-Process -Force;$p.WaitForExit(20000)|Out-Null;if(Get-Process -Id $id -ErrorAction SilentlyContinue){Fail "owned AfterFX PID $id remained running"}}}
$contractPath=Join-Path $PackageRoot 'BATCH_CONTRACT.json';$runner=Join-Path $PackageRoot 'scripts\ae_render.jsx';foreach($p in @($AfterFX,$contractPath,$runner)){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){Fail "missing $p"}}
$c=Get-Content -LiteralPath $contractPath -Raw|ConvertFrom-Json;if($c.package_id-ne'olmradialblur_type3_windows_ae_pilot_20260811'-or@($c.rows).Count-ne8){Fail 'contract identity'}
$vi=(Get-Item -LiteralPath $AfterFX).VersionInfo;if($vi.FileMajorPart-ne25-or$vi.FileMinorPart-ne2-or$vi.FilePrivatePart-ne131){Fail "AE must be 25.2x131; got $($vi.FileVersion)"}
$aex=Join-Path $PackageRoot ($c.plugin.member-replace'/','\');if((Hash $aex)-ne$c.plugin.sha256){Fail 'AEX hash'}
$canonical='C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\OLM\OLMRadialBlur.aex';$deploy=Join-Path $env:APPDATA 'Adobe\Common\Plug-ins\7.0\MediaCore\OLM_Codex_Isolated\olmrb_type3_20260811';if(Test-Path $deploy){Remove-Item -LiteralPath $deploy -Recurse -Force}
if(Test-Path -LiteralPath $canonical -PathType Leaf){if((Hash $canonical)-ne$c.plugin.sha256){Fail 'canonical OLMRadialBlur AEX hash differs; remove/replace it before pilot'};$aexRuntime=$canonical}else{New-Item -ItemType Directory -Path $deploy|Out-Null;$aexRuntime=Join-Path $deploy 'OLMRadialBlur.aex';Copy-Item -LiteralPath $aex -Destination $aexRuntime;if((Hash $aexRuntime)-ne$c.plugin.sha256){Fail 'deployed AEX hash'}}
$runRoot=Join-Path (Split-Path $PackageRoot -Parent) 'olmrb_type3_windows_run_20260811';if(Test-Path $runRoot){Remove-Item -LiteralPath $runRoot -Recurse -Force};New-Item -ItemType Directory -Path (Join-Path $runRoot 'outputs')|Out-Null
if(Get-Process AfterFX -ErrorAction SilentlyContinue){Fail 'close every AfterFX process before starting'}
foreach($row in $c.rows){if(Get-Process AfterFX -ErrorAction SilentlyContinue){Fail "pre-existing AfterFX process before $($row.row_id); close it manually"};$rowOut=Join-Path $runRoot "outputs\$($row.row_id)";New-Item -ItemType Directory -Path $rowOut|Out-Null;$ready=Join-Path $rowOut 'ready.json';$go=Join-Path $rowOut 'continue.marker';$result=Join-Path $rowOut 'result.json';$nonce=[guid]::NewGuid().ToString('N');$ownedPid=0
 $env:OLMRB_ROOT=$PackageRoot;$env:OLMRB_ROW=$row.row_id;$env:OLMRB_OUT=$rowOut;$env:OLMRB_READY=$ready;$env:OLMRB_GO=$go;$env:OLMRB_RESULT=$result;$env:OLMRB_NONCE=$nonce;$env:OLMRB_TEMPLATE=$OutputTemplate;$started=(Get-Date).ToUniversalTime();$launch=Start-Process -FilePath $AfterFX -ArgumentList @('-r',$runner) -PassThru;$ownedPid=[int]$launch.Id
 try{WaitFile $ready;$r=Get-Content $ready -Raw|ConvertFrom-Json;if($r.nonce-ne$nonce-or$r.row_id-ne$row.row_id-or$r.renderer_raw-ne1816-or$r.depth-ne32-or$r.noise_layer_written-ne$r.noise_layer_readback){Fail "ready contract $($row.row_id)"};$ps=@(Get-Process AfterFX|Where-Object{$_.StartTime.ToUniversalTime()-ge$started.AddSeconds(-2)});if($ps.Count-ne1){Fail "fresh PID cardinality $($ps.Count)"};$pidValue=[int]$ps[0].Id;$ownedPid=$pidValue;$mods=@($ps[0].Modules|Where-Object{[IO.Path]::GetFullPath($_.FileName)-ieq[IO.Path]::GetFullPath($aexRuntime)});if($mods.Count-ne1){Fail "loaded AEX module binding $($mods.Count)"};$moduleBase=('0x{0:x}'-f[Int64]$mods[0].BaseAddress);New-Item -ItemType File -Path $go|Out-Null;WaitFile $result;$ae=Get-Content $result -Raw|ConvertFrom-Json;if($ae.status-ne'ok'){Fail "$($row.row_id): $($ae.error)"};StopOwnedAE $ownedPid;$ownedPid=0;$src=[string]$ae.output_source;if(-not(Test-Path $src -PathType Leaf)){Fail 'render missing'};$dst=Join-Path $rowOut 'effect_on.exr';Move-Item $src $dst
  $att=[ordered]@{row_id=$row.row_id;case_id=$row.case_id;repeat=[int]$row.repeat;execution_row_sha256=$row.execution_row_sha256;witness_request_sha256=$c.witness_request_sha256;ae_version='25.2x131';ae_pid=$pidValue;renderer='Software';depth=32;aex_path=$aexRuntime;aex_sha256=Hash $aexRuntime;module_base=$moduleBase;source_sha256=Hash (Join-Path $PackageRoot ($row.source_member-replace'/','\'));noise_layer_sha256=Hash (Join-Path $PackageRoot ($row.noise_layer_member-replace'/','\'));noise_layer_written=[int]$ae.noise_layer_written;noise_layer_readback=[int]$ae.noise_layer_readback;noise_layer_source_name=[string]$ae.noise_layer_source_name;parameters_before=$ae.parameters_before;parameters_after=$ae.parameters_after;output_template=$OutputTemplate;output_settings=$ae.output_settings;output_member="outputs/$($row.row_id)/effect_on.exr";output_sha256=Hash $dst};Json (Join-Path $rowOut 'attestation.json') $att
 }catch{StopOwnedAE $ownedPid;throw}}
Write-Host "[OK] $runRoot";Write-Host "Run: py -3 `"$PackageRoot\VERIFY_RETURN.py`" `"$runRoot`""
