#!/usr/bin/env python3
"""Run the explicit OLMSmoother2 v2/no-key Mac AE candidate request."""
from __future__ import annotations
import argparse, hashlib, json, subprocess, sys, tempfile
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; REQUEST = ROOT / "refs/mac_validation_requests/olmsmoother2_no_key_32bpc_mac_validation_20260715.json"; STEM = "olmsmoother2_no_key_32bpc_mac_validation_20260715"
def sha256(p: Path) -> str: return hashlib.sha256(p.read_bytes()).hexdigest()
def canonical(v: object) -> str: return hashlib.sha256(json.dumps(v, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()).hexdigest()
def jsx_source(case: dict, contract_hash: str) -> str:
    c = json.dumps(case, separators=(",", ":"), ensure_ascii=True); return r'''(function(){var spec=CASE_JSON, CONTRACT=CONTRACT_JSON, TEMPLATE="OLM EXR 32 Float", API="OutputModule.getSettings(GetSettingsFormat.STRING)";
function env(n){try{return $.getenv(n)||"";}catch(e){return "";}} function fail(m){throw new Error("FAIL_CLOSED: "+m);} function q(v){return '"'+String(v).replace(/\\/g,"\\\\").replace(/"/g,'\\"')+'"';} function stable(v){if(v===null)return"null";if(typeof v==="string")return q(v);if(typeof v==="number"){if(!isFinite(v))fail("nonfinite");return String(v);}if(typeof v==="boolean")return v?"true":"false";if(v instanceof Array){var a=[];for(var i=0;i<v.length;i++)a.push(stable(v[i]));return"["+a.join(",")+"]";}if(typeof v==="object"){var k=[],o=[];for(var n in v)if(v.hasOwnProperty(n))k.push(n);k.sort();for(var j=0;j<k.length;j++)o.push(q(k[j])+":"+stable(v[k[j]]));return"{"+o.join(",")+"}";}fail("unsupported");} function write(p,s){var f=new File(p);f.encoding="UTF-8";if(!f.open("w"))fail("write "+p);f.write(s);f.close();} function sh(p){return system.callSystem("/usr/bin/shasum -a 256 '"+String(p).replace(/'/g,"'\\''")+"'").replace(/[\r\n]+$/g,"");} function hash(p){var m=sh(p).match(/^([0-9a-fA-F]{64})\s/);if(!m)fail("hash "+p);return m[1].toLowerCase();} function prop(g,n){for(var i=1;i<=g.numProperties;i++){var p=g.property(i);if(p.matchName===n)return p;if(p.numProperties){var x=prop(p,n);if(x)return x;}}return null;} function params(e){for(var i=0;i<spec.params_full.length;i++){var x=spec.params_full[i],p=prop(e,x.match_name);if(!p)fail("missing "+x.match_name);p.setValue(x.value);}} function capture(m,p){if(!m.getSettings||typeof GetSettingsFormat==="undefined")fail("settings API");var s=m.getSettings(GetSettingsFormat.STRING);var path=p.replace(/\.exr$/i,"_output_module_settings.json");write(path,stable({kind:"olm_output_module_settings_capture",output_template:TEMPLATE,capture_api:API,settings:s})+"\n");return{path:path,sha256:hash(path),serialization:stable(s)};} function render(comp,e,on,out,name){e.enabled=on;var item=app.project.renderQueue.items.add(comp);item.timeSpanStart=0;item.timeSpanDuration=1/comp.frameRate;var m=item.outputModule(1);m.applyTemplate(TEMPLATE);var p=out+"/"+name,s=capture(m,p);m.file=new File(p);app.project.renderQueue.render();if(!new File(p).exists)fail("missing output");var r={path:p,sha256:hash(p),output_module_settings:s,effect_enabled:on};item.remove();return r;}
var inputDir=env("OLM_AE_MAC_INPUT_DIR"),out=env("OLM_AE_MAC_OUTPUT_DIR"),result=env("OLM_AE_MAC_RESULT_JSON"),pluginPath=env("OLM_AE_MAC_PLUGIN_PATH");if(!inputDir||!out||!result||!pluginPath)fail("environment");var pf=new File(pluginPath);if(!pf.exists||pf.name!=="OLMSmoother2.plugin")fail("plugin identity");var plugin={filename:pf.name,path:pf.fsName,sha256:hash(pf.fsName)},pr=app.newProject();pr.bitsPerChannel=32;pr.linearBlending=false;try{pr.gpuAccelType=GpuAccelType.SOFTWARE;}catch(e){fail("SOFTWARE");}if(Number(pr.bitsPerChannel)!==32||String(pr.gpuAccelType).toUpperCase()!=="SOFTWARE"||pr.workingSpace!=="None")fail("project contract");var f=new File(inputDir+"/"+spec.input.filename);if(!f.exists)fail("input");var ft=pr.importFile(new ImportOptions(f)),cs=spec.comp,co=pr.items.addComp(spec.id,cs.width,cs.height,cs.pixel_aspect,1/cs.frame_rate,cs.frame_rate),ly=co.layers.add(ft),e=ly.property("ADBE Effect Parade").addProperty("OLM Smoother v2");if(!e||e.matchName!=="OLM Smoother v2"||e.name!=="OLM Smoother v2")fail("effect identity");params(e);var no=render(co,e,false,out,spec.id+"__no_effect.exr"),yes=render(co,e,true,out,spec.id+"__effect_on.exr");if(no.output_module_settings.serialization!==yes.output_module_settings.serialization)fail("settings differ");write(result,stable({kind:"olmsmoother2_no_key_32bpc_mac_validation_return",schema_version:1,status:"candidate_return_only",ae_exact_claim:false,ae_exact_claim_reason:"Windows artifact attestation and raw FLOAT32 comparison are pending",platform:"macOS",ae_version:app.version,case_contract_sha256:CONTRACT,project:{bits_per_channel:pr.bitsPerChannel,renderer:"SOFTWARE",working_space:pr.workingSpace,linear_blending:pr.linearBlending,comp:{width:cs.width,height:cs.height,frame_rate:cs.frame_rate}},output_module:{template_name:TEMPLATE,capture_api:API,channels:["A","B","G","R"],sample_type:"FLOAT",compression:"none"},plugin:plugin,cases:[{id:spec.id,input:spec.input,params_full:spec.params_full,effect:{name:e.name,match_name:e.matchName,enabled:true},outputs:{no_effect_control:no,effect_on:yes},no_effect_control_passed:true}]})+"\n");try{pr.close(CloseOptions.DO_NOT_SAVE_CHANGES);}catch(e){}}());'''.replace("CASE_JSON", c).replace("CONTRACT_JSON", json.dumps(contract_hash))
def main() -> int:
    ap=argparse.ArgumentParser(); ap.add_argument("--plugin-path",type=Path,required=True); ap.add_argument("--support-dir",type=Path); ap.add_argument("--output-dir",type=Path); ap.add_argument("--result-json",type=Path); ap.add_argument("--dump-js",type=Path); ap.add_argument("--app-name",default="Adobe After Effects 2026"); a=ap.parse_args()
    if a.plugin_path.name!="OLMSmoother2.plugin" or not a.plugin_path.is_file(): print("[FAIL_CLOSED] --plugin-path must name an existing OLMSmoother2.plugin"); return 2
    data=json.loads(REQUEST.read_text()); case=data["cases"][0]; support=a.support_dir or Path(tempfile.mkdtemp(prefix=STEM+"_")); (support/"input").mkdir(parents=True,exist_ok=True); src=ROOT/data["windows_reference"]["artifact_root"]/data["windows_reference"]["before_effects_frame"]
    if not src.is_file() or sha256(src)!=data["windows_reference"]["before_effects_sha256"]: print("[FAIL_CLOSED] Windows input missing or hash mismatch"); return 1
    shutil=None
    import shutil as _shutil; _shutil.copy2(src,support/"input"/src.name); out=(a.output_dir or support/"return"); out.mkdir(parents=True,exist_ok=True); result=(a.result_json or out/"mac_validation_return.json"); jsx=support/"run_mac_olmsmoother2_no_key_32bpc_validation.jsx"; ch=canonical({"request_id":data["request_id"],"case":case,"common_setup":data["common_setup"],"mac_run_contract":data["mac_run_contract"]}); jsx.write_text(jsx_source({**case,"input":{"filename":src.name,"sha256":sha256(src)}},ch),encoding="utf-8"); wrapper=support/"run_mac_wrapper.jsx"; env={"OLM_AE_MAC_INPUT_DIR":str((support/"input").resolve()),"OLM_AE_MAC_OUTPUT_DIR":str(out.resolve()),"OLM_AE_MAC_RESULT_JSON":str(result.resolve()),"OLM_AE_MAC_PLUGIN_PATH":str(a.plugin_path.resolve())}; wrapper.write_text("\n".join("$.setenv(%s,%s);"%(json.dumps(k),json.dumps(v)) for k,v in env.items())+"\n$.evalFile(new File(%s));\n"%json.dumps(str(jsx.resolve())),encoding="utf-8")
    if a.dump_js: a.dump_js.write_text(wrapper.read_text(),encoding="utf-8"); print(f"[OK] wrote {a.dump_js}"); return 0
    try: p=subprocess.run(["osascript"],input=f'tell application {json.dumps(a.app_name)} to DoScriptFile POSIX file {json.dumps(str(wrapper))} with override\n',text=True,capture_output=True,timeout=7230)
    except (OSError,subprocess.TimeoutExpired): print("[FAIL_CLOSED] AE did not produce a return"); return 1
    if p.returncode or not result.exists(): print("[FAIL_CLOSED] AE did not produce a return"); return 1
    report=subprocess.run([sys.executable,str(ROOT/"scripts/report_olmsmoother2_no_key_32bpc_mac_validation_20260715.py"),str(result),"--output-dir",str(out)],text=True); return report.returncode
if __name__=="__main__": raise SystemExit(main())
