[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$AexPath,
  [string]$CdbPath='C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe',
  [string]$AfterFxPath='C:\Program Files\Adobe\Adobe After Effects 2026\Support Files\AfterFX.exe',
  [string]$WorkRoot="$env:TEMP\olmkirakira_mode3_live_gaussian_20260713"
)
$ErrorActionPreference='Stop'
$requestId='olmkirakira_mode3_live_gaussian_20260713'; $caseId='final_random10_olm_kira_kira_03'; $expectedHash='60997c0c52207c15844a46289435231fa6b0a885f63778404e02cea6e03899f7'; $expectedSize=25781248L
$runId='kk-mode3-'+[guid]::NewGuid().ToString('N'); $work=Join-Path $WorkRoot $runId; New-Item -ItemType Directory -Force -Path $work | Out-Null
function Finish([string]$status,[hashtable]$extra,[int]$code){$body=[ordered]@{schema='olmkirakira-mode3-live-gaussian-return-v1';request_id=$requestId;status=$status;run_id=$runId}; foreach($x in $extra.GetEnumerator()){$body[$x.Key]=$x.Value}; $json=$body|ConvertTo-Json -Depth 20; $json|Set-Content -LiteralPath (Join-Path $work 'RETURN_RUNTIME_TRACE.json') -Encoding UTF8; $json; exit $code}
if(!(Test-Path -LiteralPath $AexPath -PathType Leaf)){Finish 'exact_bind_failure' @{failure=@{stage='preflight';reason='AEX absent'}} 2}
$aex=Get-Item -LiteralPath $AexPath; $hash=(Get-FileHash -Algorithm SHA256 -LiteralPath $aex.FullName).Hash.ToLowerInvariant(); if($aex.Length -ne $expectedSize -or $hash -ne $expectedHash){Finish 'exact_bind_failure' @{failure=@{stage='aex_identity';reason='size or SHA256 mismatch';sha256=$hash;size=$aex.Length}} 2}
foreach($x in @($CdbPath,$AfterFxPath)){if(!(Test-Path -LiteralPath $x -PathType Leaf)){Finish 'exact_bind_failure' @{failure=@{stage='preflight';reason='required executable absent';path=$x}} 2}}
if(Get-Process -Name AfterFX -ErrorAction SilentlyContinue){Finish 'exact_bind_failure' @{failure=@{stage='preflight';reason='After Effects must be fully closed before this run'}} 2}
$caseRoot=Join-Path $PSScriptRoot 'case'; $jsx=Join-Path $caseRoot 'ae_render_single_case.jsx'; $templatePath=Join-Path $PSScriptRoot 'mode3_live_gaussian.cdb.in'; $trace=Join-Path $work 'cdb_output.txt'; $stderr=Join-Path $work 'cdb_stderr.txt'; $ready=Join-Path $work 'ae_ready.marker'; $continue=Join-Path $work 'ae_continue.marker'; $words=Join-Path $work 'gaussian_kernel_21_f32_le.bin'
foreach($x in @($jsx,$templatePath,(Join-Path $caseRoot 'request_manifest.json'),(Join-Path $caseRoot 'reference_manifest.json'),(Join-Path $caseRoot 'input\case_03_before_effects.png'))){if(!(Test-Path -LiteralPath $x -PathType Leaf)){Finish 'exact_bind_failure' @{failure=@{stage='package';reason='required package asset missing';path=$x}} 3}}
$env:OLM_AE_REQUEST_DIR=($caseRoot -replace '\\','/'); $env:OLM_AE_CASE_ID=$caseId; $env:OLM_AE_OUTPUT_DIR=Join-Path $work 'render'; $env:OLM_AE_LOG_PATH=Join-Path $work 'ae_render.log'; $env:OLM_AE_RESULT_JSON=Join-Path $work 'ae_render_result.json'; $env:OLM_AE_PARAM_OVERRIDES_JSON='{"OLM OLM Kira Kira-0003":5,"OLM OLM Kira Kira-0004":0,"OLM OLM Kira Kira-0005":0,"OLM OLM Kira Kira-0026":0}'; $env:OLM_AE_FORCE_SOFTWARE='1'; $env:OLM_AE_FORCE_NEW_PROJECT='1'; $env:OLM_AE_KEEP_OPEN='0'; $env:OLM_AE_PAUSE_BEFORE_RENDER='1'; $env:OLM_AE_READY_MARKER=$ready; $env:OLM_AE_CONTINUE_MARKER=$continue; New-Item -ItemType Directory -Force -Path $env:OLM_AE_OUTPUT_DIR | Out-Null
$launchDir=Join-Path $env:PUBLIC ('OLMTrace\'+$runId); New-Item -ItemType Directory -Force -Path $launchDir | Out-Null; $jsxLaunch=Join-Path $launchDir 'runner.jsx'; Copy-Item -LiteralPath $jsx -Destination $jsxLaunch -Force; if($jsxLaunch -match '\s'){Finish 'exact_bind_failure' @{failure=@{stage='preflight';reason='no-space JSX launch path invariant failed';path=$jsxLaunch}} 3}
$ae=Start-Process -FilePath $AfterFxPath -ArgumentList ('-m -r '+$jsxLaunch) -PassThru; $deadline=(Get-Date).AddSeconds(180); while((Get-Date)-lt $deadline -and !(Test-Path -LiteralPath $ready)){Start-Sleep -Milliseconds 250}; if(!(Test-Path -LiteralPath $ready)){Finish 'exact_bind_failure' @{failure=@{stage='ae_ready';reason='ready marker missing'}} 4}
$module=$null; $deadline=(Get-Date).AddSeconds(30); while((Get-Date)-lt $deadline -and $null -eq $module){try{$module=(Get-Process -Id $ae.Id -ErrorAction Stop).Modules|Where-Object{$_.FileName -ieq $aex.FullName}|Select-Object -First 1}catch{}; if($null -eq $module){Start-Sleep -Milliseconds 250}}; if($null -eq $module){Finish 'exact_bind_failure' @{failure=@{stage='module_lookup';reason='hash-pinned AEX not loaded at ready marker';pid=$ae.Id}} 4}
$base=('0x{0:x}' -f $module.BaseAddress.ToInt64()); $wrapper=('0x{0:x}' -f ($module.BaseAddress.ToInt64()+0x1272ec0)); $create=('0x{0:x}' -f ($module.BaseAddress.ToInt64()+0x1266730)); $kernel=('0x{0:x}' -f ($module.BaseAddress.ToInt64()+0x12754a0)); $cdb=Join-Path $work 'mode3_live_gaussian.cdb'; $text=(Get-Content -LiteralPath $templatePath -Raw).Replace('__TRACE__',$trace).Replace('__RUN_ID__',$runId).Replace('__BASE__',$base).Replace('__WRAPPER__',$wrapper).Replace('__CREATE__',$create).Replace('__KERNEL__',$kernel).Replace('__WORDS__',$words); if(($cdb,$words)|Where-Object{$_ -match '\s'}){Finish 'exact_bind_failure' @{failure=@{stage='preflight';reason='CDB artifact path contains whitespace'}} 3}; $text|Set-Content -LiteralPath $cdb -Encoding ASCII
$proc=Start-Process -FilePath $CdbPath -ArgumentList ('-cf "'+$cdb+'" -p '+$ae.Id) -RedirectStandardOutput $trace -RedirectStandardError $stderr -NoNewWindow -PassThru; $deadline=(Get-Date).AddSeconds(60); while((Get-Date)-lt $deadline){if((Test-Path $trace)-and((Get-Content $trace -Raw)-match 'KK_BREAKPOINTS_READY')){break}; Start-Sleep -Milliseconds 250}; if(!(Test-Path $trace)-or -not((Get-Content $trace -Raw)-match 'KK_BREAKPOINTS_READY')){Finish 'exact_bind_failure' @{failure=@{stage='hook_install';reason='absolute base+RVA breakpoints not armed';base=$base}} 4}; Set-Content -LiteralPath $continue -Value continue -Encoding ASCII; $proc|Wait-Process; $lines=if(Test-Path $trace){@(Get-Content -LiteralPath $trace)}else{@()}; $joined=$lines -join [Environment]::NewLine
function Marker([string]$n){$lines|Where-Object{$_ -match "^$n\s"}|Select-Object -Last 1}; function Field([string]$l,[string]$k){$m=[regex]::Match($l,"(?:^|\s)$k=([^\s]+)");if($m.Success){$m.Groups[1].Value}}
$start=Marker 'KK_RUN_START'; $mod=Marker 'KK_MODULE'; $wrap=Marker 'KK_WRAPPER'; $cr=Marker 'KK_CREATE'; $ke=Marker 'KK_KERNEL_ENTRY'; $kr=Marker 'KK_KERNEL_RETURN'; $missing=New-Object System.Collections.Generic.List[string]; foreach($p in @(@('run_start',$start),@('module',$mod),@('wrapper',$wrap),@('create',$cr),@('kernel_entry',$ke),@('kernel_return',$kr))){if(!$p[1]){[void]$missing.Add($p[0])}}
if(!$ke -or (Field $ke 'ecx') -ne '21'){[void]$missing.Add('kernel_ecx_21')}; if(!$ke -or (Field $ke 'r8') -ne '5'){[void]$missing.Add('kernel_r8_5')}; if(!$ke -or [double](Field $ke 'xmm1') -ne 2.5){[void]$missing.Add('kernel_xmm1_2.5')}; if(!$kr -or (Field $kr 'word_count') -ne '21'){[void]$missing.Add('word_count_21')}; if(!(Test-Path -LiteralPath $words)){[void]$missing.Add('raw_words_file')}; elseif((Get-Item -LiteralPath $words).Length -ne 84){[void]$missing.Add('raw_words_size_84')}; $ids=@($lines|ForEach-Object{if($_ -match '^KK_\S+.*run_id=([^\s]+)'){$Matches[1]}}|Sort-Object -Unique); if($ids.Count -ne 1){[void]$missing.Add('same_run_identity')}; if(!$start -or (Field $start 'case_id') -ne $caseId){[void]$missing.Add('case_identity')}; if($missing.Count){Finish 'exact_bind_failure' @{failure=@{stage='binding';reason='required live markers or exact first-kernel fields missing';missing=@($missing);same_run_ids=$ids;trace=$joined}} 4}
$raw=[IO.File]::ReadAllBytes($words); $u32=for($i=0;$i -lt 21;$i++){[BitConverter]::ToUInt32($raw,$i*4).ToString('x8')}; Finish 'answered' @{run=@{run_id=$ids[0];case_id=$caseId;module='OLMKiraKira.aex';module_base=$base;aex_sha256=$hash;aex_size=$aex.Length};binding=@{wrapper_rva='0x1272ec0';create_rva='0x1266730';getKernel_rva='0x12754a0';wrapper=$wrapper;create=$create;getKernel=$kernel};case=@{blur_mode_manifest=3;overrides_match_name=@{'OLM OLM Kira Kira-0003'=5;'OLM OLM Kira Kira-0004'=0;'OLM OLM Kira Kira-0005'=0;'OLM OLM Kira Kira-0026'=0}};observation=@{module_marker=$mod;wrapper_marker=$wrap;create_marker=$cr;first_getKernel=@{ecx=[int](Field $ke 'ecx');xmm1=[double](Field $ke 'xmm1');r8=[int](Field $ke 'r8');output_mat=(Field $ke 'output_mat')};return_data=(Field $kr 'data');raw_words_u32=$u32;raw_bytes=84};trace=$joined} 0
