$.setenv("CK_INPUT","/Users/onmk/Documents/Projects/Personal/OLM as/refs/mac_validation_fixtures/colorkeep_pf16_extended_host_20260806/input_pf16_units_as_float.exr");
$.setenv("CK_OUT","/Users/onmk/Documents/Projects/Personal/OLM as/refs/mac_validation_runs/colorkeep_pf16_extended_host_20260806_run2/output");
$.setenv("CK_RESULT","/Users/onmk/Documents/Projects/Personal/OLM as/refs/mac_validation_runs/colorkeep_pf16_extended_host_20260806_run2/candidate_return.json");
$.setenv("CK_ERROR","/Users/onmk/Documents/Projects/Personal/OLM as/refs/mac_validation_runs/colorkeep_pf16_extended_host_20260806_run2/error.log");
$.setenv("CK_BINARY","/Users/onmk/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/ColorKeep.plugin/Contents/MacOS/ColorKeep");
$.setenv("CK_TEMPLATE","/Users/onmk/Documents/Projects/Personal/OLM as/refs/fixtures/olmsmoother2_32bpc_preserve_rgb_input_template_20260726.aep");
(function(){
function E(n){return $.getenv(n)||"";}function F(m){throw new Error("FAIL_CLOSED: "+m);}function Q(v){return '"'+String(v).replace(/\\/g,"\\\\").replace(/"/g,'\\"')+'"';}
function SQ(v){var q=String.fromCharCode(39),s=String.fromCharCode(92);return q+String(v).split(q).join(q+s+q+q)+q;}function H(p){var x=system.callSystem("/usr/bin/shasum -a 256 "+SQ(p)),m=x.match(/^([0-9a-f]{64})/i);if(!m)F("hash "+p);return m[1].toLowerCase();}
function W(p,t){var f=new File(p);f.encoding="UTF-8";if(!f.open("w"))F("write "+p);f.write(t);f.close();}
function R(comp,e,on,name){e.enabled=on;var q=app.project.renderQueue.items.add(comp),om=q.outputModule(1),p=E("CK_OUT")+"/"+name;om.applyTemplate("OLM EXR 32 Float");om.file=new File(p);var settings=om.getSettings(GetSettingsFormat.STRING);app.project.renderQueue.render();var f=new File(p);if(!f.exists){var a=f.parent.getFiles(f.name+"*");if(a.length!==1)F("render cardinality "+a.length);f=a[0];}q.remove();return {path:f.fsName,sha256:H(f.fsName),settings:settings};}
try{var S={"keys":[[1.0,1.0,1.0],[0.25,0.75,1.0],[0.0,0.0,0.0]],"input_sha":"0d7d0a018372cb321f04ea5ad16b5542bbdc8a04453271b32b5c212f84de4459"},input=new File(E("CK_INPUT")),result=E("CK_RESULT"),binary=new File(E("CK_BINARY")),template=new File(E("CK_TEMPLATE"));if(!input.exists||H(input.fsName)!==S.input_sha||H(binary.fsName)!=="ccc89781fa547450acc3053cb77bff8d6983cd8c6835866c87449e7a64117cce"||!template.exists)F("identity");if(app.project)try{app.project.close(CloseOptions.DO_NOT_SAVE_CHANGES);}catch(_e){}
var p=app.open(template);p.bitsPerChannel=16;p.workingSpace="";p.linearBlending=false;p.gpuAccelType=GpuAccelType.SOFTWARE;if(p.bitsPerChannel!==16||Number(p.gpuAccelType)!==Number(GpuAccelType.SOFTWARE))F("project contract");var ft=null,c=null;for(var ii=1;ii<=p.numItems;ii++){var it=p.item(ii);if(it.name==="OLM_COLOR_PROBE_INPUT")ft=it;if(it.name==="OLM_COLOR_PROBE_COMP")c=it;}if(!ft||!c)F("Preserve RGB template items");ft.replace(input);c.width=4;c.height=4;c.duration=1;c.frameRate=1;var l=c.layer(1);l.property("ADBE Transform Group").property("ADBE Position").setValue([2,2]);while(p.renderQueue.numItems)p.renderQueue.item(p.renderQueue.numItems).remove();var parade=l.property("ADBE Effect Parade");while(parade.numProperties)parade.property(parade.numProperties).remove();var fx=parade.addProperty("OLM Color Keep");if(!fx||fx.matchName!=="OLM Color Keep"||fx.numProperties!==102)F("effect surface");fx.property(1).setValue(S.keys.length);var read=[];for(var i=0;i<S.keys.length;i++){var k=S.keys[i];fx.property(i+2).setValue([k[0],k[1],k[2],1]);var v=fx.property(i+2).value;if(Math.abs(v[0]-k[0])>1e-7||Math.abs(v[1]-k[1])>1e-7||Math.abs(v[2]-k[2])>1e-7)F("RGB readback "+i);read.push([v[0],v[1],v[2]]);}var no=R(c,fx,false,"control.exr"),yes=R(c,fx,true,"effect_on.exr");W(result,JSON.stringify({status:"candidate_return_only",ae_exact_claim:false,ae_version:app.version,bits_per_channel:p.bitsPerChannel,renderer:"SOFTWARE",working_space:"None",linear_blending:p.linearBlending,plugin_sha256:H(binary.fsName),input_interpretation:"hash_bound_preserve_rgb_template",template_sha256:H(template.fsName),public_rgb_readback:read,outputs:{control:no,effect_on:yes}}));try{p.close(CloseOptions.DO_NOT_SAVE_CHANGES);}catch(_c){}
}catch(e){W(E("CK_ERROR"),String(e)+" line="+String(e.line||""));}}());